[package]
name = "webm"
version = "0.2.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MPL-2.0"
repository = "https://github.com/DiamondLovesYou/rust-webm"
description = "Rust idiomatic wrapper to libwebm"
keywords = [ "webm" ]

[lib]
name = "webm"
path = "src/lib/lib.rs"

[dependencies.webm-sys]
path = "src/sys"
version = "0.1"

[dependencies]
libc = "*"
