[package]
authors = [
    "Richard Diamond <wichard@vitalitystudios.com>",
    "Kornel Lesiński <kornel@geekhood.net>",
]
description = "Rust idiomatic wrapper to libwebm"
keywords = ["webm"]
license = "MPL-2.0"
name = "webm-native"

repository = "https://github.com/pornel/rust-webm.git"
version = "0.4.1"

[dependencies]
libc = "0.2.20"
webm-sys-native = { version = "0.3.1", path = "src/sys" }

[lib]
name = "webm"
path = "src/lib/lib.rs"

