[package]
authors = [
    "Kornel Lesiński <kornel@geekhood.net>",
    "Richard Diamond <wichard@vitalitystudios.com>",
]
description = "Rust idiomatic wrapper to libwebm"
keywords = ["webm"]
license = "MPL-2.0"
name = "webm"
readme = "README.md"
repository = "https://github.com/DiamondLovesYou/rust-webm.git"
categories = [ "multimedia::video", "multimedia::encoding", "api-bindings" ]
version = "0.4.5"

[dependencies]
webm-sys = { version = "0.3.5", path = "src/sys" }

[lib]
name = "webm"
path = "src/lib/lib.rs"

