[package]
name = "webm-sys"
version = "0.1.1"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MPL-2.0"
repository = "https://github.com/DiamondLovesYou/rust-webm"
description = "Rust bindings to libwebm"
build = "build.rs"

[build-dependencies]
pnacl-build-helper = "1.4"

[lib]
name = "webm_sys"
path = "lib.rs"

[dependencies]
libc = "0.2"
